name = "pthreads"
uuid = "67e7e89d-5a76-441b-8d18-ff2e035d61a7"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
pthread_win32_jll = "390092ed-c679-5f41-b9a2-7c2415b692fd"

[compat]
julia = "1.9"
